name: Release
on:
  push:
    tags:
      - '*'
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create better-d2-lfg-experience Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'better-d2-lfg-experience.zip'
          exclusions: '*.git*'
      - name: Upload better-d2-lfg-experience Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'better-d2-lfg-experience.zip'
          token: ${{ secrets.GITHUB_TOKEN }}